trigger:
- main

pool:
  name: 'Default'  # Replace with your actual self-hosted agent pool name
  demands:
    - Agent.Name -equals MyAgent  # Replace with your specific agent's name

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
